### ISSUE TITLE
训练时遇到问题，提示如下

### ISSUE THREAD

**Issue by zzff-sys** [TomMao23/multiyolov5#20]
## ❔Question
作者你好，请问我在训练的时候train_custom.py的时候出现错误File "train_custom.py", line 641, in <module>
train(hyp, opt, device, tb_writer)
File "train_custom.py", line 463, in train
f.write(s + '%10.4g' * 7 % results + '\n') # append metrics, val_loss
UnboundLocalError: local variable 's' referenced before assignment

**Comment by hfutwqs** [comment]
你把batch_size改小一点就行了，因为这个训练集数据少，batch_size默认为16

**Comment by zzff-sys** [comment]
谢谢了，确实是这个问题，问题解决 @hfutwqs

**Comment by lyxbyr** [comment]
@zzff-sys @hfutwqs @TomMao23 我怎么训练会报这个错，你们没有遇到？？？


RuntimeError: cuDNN error: CUDNN_STATUS_INTERNAL_ERROR
You can try to repro this exception using the following code snippet. If that doesn't trigger the error, please include your original repro script when reporting this issue.

import torch
torch.backends.cuda.matmul.allow_tf32 = True
torch.backends.cudnn.benchmark = True
torch.backends.cudnn.deterministic = False
torch.backends.cudnn.allow_tf32 = True
data = torch.randn([8, 128, 52, 104], dtype=torch.half, device='cuda', requires_grad=True)
net = torch.nn.Conv2d(128, 2, kernel_size=[1, 1], padding=[0, 0], stride=[1, 1], dilation=[1, 1], groups=1)
net = net.cuda().half()
out = net(data)
out.backward(torch.randn_like(out))
torch.cuda.synchronize()

ConvolutionParams
data_type = CUDNN_DATA_HALF
padding = [0, 0, 0]
stride = [1, 1, 0]
dilation = [1, 1, 0]
groups = 1
deterministic = false
allow_tf32 = true
input: TensorDescriptor 000001F1E879F590
type = CUDNN_DATA_HALF
nbDims = 4
dimA = 8, 128, 52, 104,
strideA = 692224, 5408, 104, 1,
output: TensorDescriptor 000001F1E879F670
type = CUDNN_DATA_HALF
nbDims = 4
dimA = 8, 2, 52, 104,
strideA = 10816, 5408, 104, 1,
weight: FilterDescriptor 000001F1A0BDA0D0
type = CUDNN_DATA_HALF
tensor_format = CUDNN_TENSOR_NCHW
nbDims = 4
dimA = 2, 128, 1, 1,
Pointer addresses:
input: 000000078F464000
output: 0000000765FC1E00
weight: 0000000765DFFE00
